seed_everything: 34234
trainer:
  max_epochs: 50

model: fcn.yaml

data:
  __base__: fordA.yaml
  init_args:
    batch_size: 64
    lambda_time: 10000
    lambda_freq: 1000

optimizer:
  lr: 0.0006346430788611747