__base__: mechanical_base.yaml

model: 
  __base__: fcn.yaml
  init_args:
    right_reason_loss: lib.loss.RRRIGLoss

data:
  __base__: mechanical_conf.yaml
  init_args:
    lambda_time: 100
    feedback_penalty_range: [1380:1600, 2080:2500]