seed_everything: 34235
trainer:
  max_epochs: 20

model: fcn.yaml

data:
  __base__: mechanical.yaml
  init_args:
    batch_size: 64
    lambda_time: 100
    feedback_penalty_range: [1380:1600, 2080:2500]

optimizer:
  lr: 1e-3