seed_everything: 34235
trainer:
  max_epochs: 60

model: fcn.yaml

# data:
#   __base__: mechanical.yaml
#   init_args:
#     batch_size: 64
#     lambda_time: 100

optimizer:
  class_path: torch.optim.Adam
  # lr: 0.000524291743023029
  init_args:
    lr: 1e-3