seed_everything: 34234
trainer:
  max_epochs: 95 


model: tide.yaml 

data: 
  __base__: source_energy.yaml
  init_args:
    batch_size: 512
    lambda_time: 10000.0 # good default, but could be improved
    lookback: 101
    prediction_horizon: 34 

optimizer:
  lr: 1e-3