seed_everything: 34234
trainer:
  max_epochs: 95 


model: tide.yaml 

data: 
  __base__: source_ettm1.yaml
  init_args:
    batch_size: 512
    # lambda_freq: 1000 
    lambda_freq: 512 
    # lookback: 50
    # prediction_horizon: 16 
    lookback: 101
    prediction_horizon: 34 
    confounder_freq_len: 2
    confounder_freq_strength: 10000

optimizer:
  lr: 1e-3