seed_everything: 34234
trainer:
  max_epochs: 150 


model: patchtst.yaml 

data: 
  __base__: source_ettm1.yaml
  init_args:
    batch_size: 512 
    lambda_time:  25 
    lambda_freq: 500000 # 10000 
    lookback: 101
    prediction_horizon: 34
    confounder_freq_len: 3
    confounder_freq_strength: 6000

optimizer:
  lr: 5e-3